### ISSUE TITLE
ERROR in production

### ISSUE THREAD

**Issue by RobRuana** [magfest/panels#92]
Looks like we were expecting `normalize_newlines` to have been imported in `uber.common` and it wasn't.
```
   Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 239, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 230, in with_caching
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 254, in with_session
        retval = func(*args, session=session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 375, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 315, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 148, in csvout
        func(self, csv.writer(writer), session, **kwargs)
      File "/usr/local/uber/plugins/panels/panels/site_sections/schedule.py", line 105, in csv
        normalize_newlines(event.description).replace('\n', ' '),
    NameError: name 'normalize_newlines' is not defined
```

**Comment by RobRuana** [comment]
For what it's worth, this is another bug that would have been caught by `flake8`.
